on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: "Go"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Code checkout
        uses: actions/checkout@v1
      - name: Build
        env:
          GO111MODULE: on
        run: |
          make test
      - name: Publish coverage
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
