on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: "Go"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Tests
        uses: cedrickring/golang-action/go1.13@1.4.1
        env:
          GO111MODULE: "on"
          IMPORT: "github.com/universe-sh/client-go"
        with:
          args: make test
